### PR TITLE
Numpy >1.18 compatibility

### PR DESCRIPTION
**Pull request by bsteubing**
A "TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer." is thrown by numpy >1.18 in the linspace function in the delta analysis. `int(round(M))` should fix this issue.

### CODE REVIEW

**Comment by jdherman** [comment]
Thanks @bsteubing . This should work. The Travis build error seems to have nothing to do with the code change. 

Anyone know why this error is happening? (python 3.5 only). It looks like it's part of the pandas installer script, not from our config.
```
Running pandas-1.0.0rc0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-oug8wx74/pandas-1.0.0rc0/egg-dist-tmp-s7ow2ms9
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 44, in _execfile
    code = compile(script, filename, 'exec')
  File "/tmp/easy_install-oug8wx74/pandas-1.0.0rc0/setup.py", line 42
    f"numpy >= {min_numpy_ver}",
                              ^
SyntaxError: invalid syntax
```

**Comment by willu47** [comment]
Python 3.5 is no longer supported by conda, so it could be that there are some builds that are not working for some dependencies and therefore bugs introduced (or not fixed).

**Comment by ConnectedSystems** [comment]
This specific error is caused by the use of `f` string formatting which was introduced in Python 3.6 (https://www.python.org/dev/peps/pep-0498/)

Are we able to specify which pandas version Py3.5 installs should use?

Alternatively, we could deprecate support for Python 3.5 in the near future. Other packages are talking of doing the same (e.g. https://github.com/Qiskit/qiskit-terra/pull/3268).

**Comment by bsteubing** [comment]
> 
> 
> Thanks @bsteubing . This should work. The Travis build error seems to have nothing to do with the code change.
> 
> Anyone know why this error is happening? (python 3.5 only). It looks like it's part of the pandas installer script, not from our config.
> 
> ```
> Running pandas-1.0.0rc0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-oug8wx74/pandas-1.0.0rc0/egg-dist-tmp-s7ow2ms9
> Traceback (most recent call last):
>   File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 154, in save_modules
>     yield saved
>   File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 195, in setup_context
>     yield
>   File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 250, in run_setup
>     _execfile(setup_script, ns)
>   File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 44, in _execfile
>     code = compile(script, filename, 'exec')
>   File "/tmp/easy_install-oug8wx74/pandas-1.0.0rc0/setup.py", line 42
>     f"numpy >= {min_numpy_ver}",
>                               ^
> SyntaxError: invalid syntax
> ```

Came across this again. I think it has nothing to do with Python 3.5 but instead with new versions of numpy (>1.18). 
@jdherman what do you think? Could this pull request be accepted? (for now our hack is to manually change the delta.py module, which is not very handy...

**Comment by willu47** [comment]
Bit confused by this error.  Does anyone @bsteubing @jdherman know - is this caused by the numpy 1.18 and python 3.5 combination, and so we should just constrain the dependencies to ensure these are not installed together, or is this a more fundamental problem?

**Comment by ConnectedSystems** [comment]
Hi @willu47 

As I stated in https://github.com/SALib/SALib/pull/280#issuecomment-575954197 the specific error being raised:

```
File "/tmp/easy_install-oug8wx74/pandas-1.0.0rc0/setup.py", line 42
    f"numpy >= {min_numpy_ver}",
                              ^
SyntaxError: invalid syntax
```
 is due to Python 3.5 not supporting `f` formatted strings. 

This was a feature introduced in Python 3.6 **and is not available in Python 3.5**
https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

The error being raised, at least as shown, does not originate from Numpy, but rather the minimum version check done by the setup process for Pandas as stated by @jdherman

**Comment by ConnectedSystems** [comment]
Also note that Pandas v1.0 onwards only supports Python 3.6 and above:

https://pandas.pydata.org/pandas-docs/version/1.0.0/getting_started/install.html#python-version-support

**Pull request merged**
