### PR TITLE
Add wheel package as required for installation

### LINKED ISSUE #438: Missing dependency on wheel
Hi!

Installation of 1.4 via pip fails for me on Ubuntu 20.04.2:

```console
rm -rf ~/.cache # delete all cached things, e.g. wheels

cd /tmp
rm -rf salib_venv

python3 -m venv salib_venv
source salib_venv/bin/activate
pip install salib
...
Building wheels for collected packages: salib
  Building wheel for salib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /tmp/salib_venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-v_9ogr6n/salib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-v_9ogr6n/salib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-aapgzyt_
       cwd: /tmp/pip-install-v_9ogr6n/salib/
  Complete output (7 lines):
  WARNING: The wheel package is not available.
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for salib
```

If I do `pip install wheel` prior to `pip install salib` the installation succeeds.

Thanks,

Sebastian

### PR DESCRIPTION
**Pull request by ConnectedSystems**
Resolves #438

### CODE REVIEW

**Comment by ConnectedSystems** [comment]
@schmitts This appears to resolve the issue on my linux box, would you be able to doubly confirm?

**Comment by schmitts** [comment]
I can confirm that `pip install .` works with this PR.

**Comment by ConnectedSystems** [comment]
@schmitts I just made a hotfix release (v1.4.0.1) for you, though like last time it may take some time for it to appear on PyPI for you.

Thanks for catching this! As a conda/pip user it did not cross my mind that other installation approaches might face issues.

**Comment by schmitts** [comment]
Can we please revert the dependency on `wheel`? It turned out to be caused by an outdated version of `pip` on my side. I've learned that one should always update `pip` first (`pip install --upgrade pip`) ... Cf. discussion here https://github.com/spack/spack/pull/25403.

**Pull request merged**
