### PR TITLE
Update landing page

### PR DESCRIPTION
**Pull request by tupui**
Fix links and update the list of methods.

I am also hopping that adding some spaces around the code blocks would allow them to be rendered properly. The preview of the markdown looks ok.

### CODE REVIEW

**Comment by ConnectedSystems** [comment]
Hi @tupui, this looks like its for the github pages (http://salib.github.io/SALib/) - is that correct?

I have half a mind to remove it given we link to ReadTheDocs in the readme, and it constitutes a (small) duplication and maintenance burden.

@willu47 any thoughts here?

I'll accept the changes for now, however.

**Comment by tupui** [comment]
I agree that as it is there is not much value in having this page. I would also remove it. Only thing to consider is that it might break some links if people are using this. I don't know here if that's relevant.

For the CI. I think we can ignore since this does not need to be built on RTD. It would just be GH rendering the readme.

**Comment by willu47** [comment]
Hi. I would be happy removing this landing page, but I'd suggest setting up forwarding to the read-the-docs so as not to break to the URL.  I know some citations that reference this URL, and not the GitHub repo, for example.

**Comment by tupui** [comment]
Ok I will make another PR with the redirect 👍 (I got to the same link before you edited your comment 😅)

**Comment by ConnectedSystems** [comment]
Closing as this is addressed by #574

**Pull request closed without merging**
