### PR TITLE
Raise error if singular matrix is detected

### PR DESCRIPTION
**Pull request by ConnectedSystems**
Raise error with message indicating sample size may be too small

Address PR #152

### CODE REVIEW

**Comment by willu47** [comment]
@ConnectedSystems - I note the current tests fail as this new error is raised for the sample sizes of 8,000 and 10,000!

**Comment by ConnectedSystems** [comment]
Hi Will,

Yes - was looking into it but then got distracted with the other request - will respond soon

**Comment by antonia-had** [comment]
Hi, was wondering what the status of this is? I keep getting it for large samples (10000) also, I believe it might also be caused if the model output is not sufficiently variant/contains many zeros (the case with mine)

**Comment by jdherman** [comment]
Hi @antonia-had , I just pushed a new release (v1.3.4) to pypi. This includes the bug fixes that were merged in this PR.

**Pull request merged**
