### PR TITLE
Example of a Sobol analysis on a parabola

### PR DESCRIPTION
**Pull request by schmitts**

### CODE REVIEW

**Comment by schmitts** [comment]
example_parabola

**Comment by ConnectedSystems** [comment]
Hello @schmitts 

Thank you for adding this example. The content looks good to me, I have only one request.

Would you mind moving the figure file into a separate directory? An "assets" folder is the usual location (e.g., `docs/assets`), which helps keep the project documentation structure tidy.

**Comment by schmitts** [comment]
Hi @ConnectedSystems!

Thanks. I'll update the PR.

**Comment by schmitts** [comment]
@ConnectedSystems Thanks for taking my PR. Does readthedocs needs a nudge? https://salib.readthedocs.io/en/latest/basics.html is not updated yet.

**Comment by ConnectedSystems** [comment]
Hi @schmitts 

Sorry, I should have communicated this to you earlier. I am in the process of moving things over to use the `main` branch instead of the previous primary branch to conform with recent trends. Simultaneously I am readying a v1.4 release which will include, amongst many other things, changes to address the issue you raised (#425) and this documentation enhancement.

This means there will be some delay in "officially" including your changes. I'll be having a look at switching over the documentation build soon.

Thanks for your patience

**Comment by schmitts** [comment]
No worries. Thanks for preparing the new release.

**Pull request merged**
