### PR TITLE
Updates package to use pyscaffold v4

### PR DESCRIPTION
**Pull request by sanjayankur31**
I wasn't sure what to do with the new files that pyscaffold v4 created, so I've put them in a separate second commit.

### CODE REVIEW

**Comment by ConnectedSystems** [comment]
Hi @sanjayankur31 

Welcome to our community and thank you very much for kickstarting this. 
I will try to make time to review this as soon as I can.

**Comment by sanjayankur31** [comment]
Thanks @ConnectedSystems .

I'm part of the NeuroFedora initiative and ran into this while updating SALib to the latest version downstream, where we now have pyscaffold v4. (I'm still working on this, need to include pathos)

https://neuro.fedoraproject.org
https://src.fedoraproject.org/rpms/python-SALib

**Comment by ConnectedSystems** [comment]
Thanks again @sanjayankur31 you seem to have done all the set up for us.

@willu47 this version of PyScaffold uses tox to manage test runs, publish packages and build/deploy documentation. Would you have the time to look through and update/streamline the travis build process?

**Comment by ConnectedSystems** [comment]
Actually, @willu47 I'm not sure that the travis config needs to be modified, although it would be nice to have docs deployed automatically. If this is handled elsewhere, then I think my question can be ignored and this PR be merged.

**Comment by willu47** [comment]
Docs are deployed using Read the Docs and Travis is not involved. I'll need to check the new configuration as the current deployment requires a key for PyPi and various other pieces. I'll assign myself to review.

**Comment by willu47** [comment]
Starting my review now back from holiday.

**Comment by schmitts** [comment]
Thanks. I'll check the Spack build once merged. Can we have a new minor version? I would like to update the Spack package.

**Comment by schmitts** [comment]
https://github.com/spack/spack/pull/25403

**Pull request merged**
