### PR TITLE
Release v1.1.0

### PR DESCRIPTION
**Pull request by willu47**
Preparing a new release

### CODE REVIEW

**Comment by jdherman** [comment]
Sounds good! Thanks Will. Do I need to push a new tag for the automatic deployment?

**Comment by willu47** [comment]
Yep, after merging, pull down the changes, tag the version and push with tags to start the auto-deployment!

**Comment by jdherman** [comment]
It worked!! https://pypi.python.org/pypi/SALib/1.1.0

Thanks @willu47

**Comment by willu47** [comment]
👍

**Pull request merged**
