### PR TITLE
Use pydata-sphinx-theme

### LINKED ISSUE #520: Use pydata-sphinx-theme
Are you interested in using the PyData-Sphinx theme? This theme is used by an increasing number of libraries including SciPy, NumPy and Pandas.

https://pydata-sphinx-theme.readthedocs.io

I can do the work if wanted 😃

### LINKED ISSUE #531: Readme installation instructions are out of data
Following the update to hatchling (#527), there is no setup.py file, so `pip install -e .` and `python setup.py install` no longer work, but are still listed in the `readme.rst` file.

### PR DESCRIPTION
**Pull request by tupui**
Closes #520, closes #531

cc @sahin-abdullah

### CODE REVIEW

**Comment by tupui** [comment]
Work in progress with Abdullah.

**Comment by tupui** [comment]
@ConnectedSystems these are the first steps towards using the new theme.

Now polishing could consist in adding a logo, changing the landing page (see SciPy or NumPy for examples) and deciding on which elements should be in the navbar. By default, Sphinx themes are using the toctree which is present in the index page. So I would suggest only keeping a few elements here (again see SciPy for an example).

I allowed edits by maintainers on this branch and showed @sahin-abdullah how to build the doc on his machine.

Happy to help more there.

**Comment by willu47** [comment]
ReadTheDocs is failing with the following error:
```python
Running Sphinx v5.1.1

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/sphinx/config.py", line 347, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/conf.py", line 102, in <module>
    import SALib
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/../src/SALib/__init__.py", line 1, in <module>
    from SALib.util import ProblemSpec
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/../src/SALib/util/__init__.py", line 8, in <module>
    import numpy as np  # type: ignore
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/numpy/__init__.py", line 144, in <module>
    from . import core
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/bin/python"
  * The NumPy version is: "1.22.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/sphinx/application.py", line 201, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/sphinx/config.py", line 169, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/sphinx/config.py", line 360, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/sphinx/config.py", line 347, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/conf.py", line 102, in <module>
    import SALib
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/../src/SALib/__init__.py", line 1, in <module>
    from SALib.util import ProblemSpec
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/../src/SALib/util/__init__.py", line 8, in <module>
    import numpy as np  # type: ignore
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/numpy/__init__.py", line 144, in <module>
    from . import core
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/bin/python"
  * The NumPy version is: "1.22.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'



Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/sphinx/config.py", line 347, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/conf.py", line 102, in <module>
    import SALib
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/../src/SALib/__init__.py", line 1, in <module>
    from SALib.util import ProblemSpec
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/../src/SALib/util/__init__.py", line 8, in <module>
    import numpy as np  # type: ignore
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/numpy/__init__.py", line 144, in <module>
    from . import core
  File "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/lib/pypy3.9/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/home/docs/checkouts/readthedocs.org/user_builds/salib/conda/523/bin/python"
  * The NumPy version is: "1.22.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'


Creating file /home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/api/SALib.rst.
Creating file /home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/api/SALib.analyze.rst.
Creating file /home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/api/SALib.plotting.rst.
Creating file /home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/api/SALib.sample.rst.
Creating file /home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/api/SALib.sample.morris.rst.
Creating file /home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/api/SALib.scripts.rst.
Creating file /home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/api/SALib.test_functions.rst.
Creating file /home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/api/SALib.util.rst.
Creating file /home/docs/checkouts/readthedocs.org/user_builds/salib/checkouts/523/docs/api/modules.rst.
```

**Comment by tupui** [comment]
Yes I am not sure what is going on here. I will dig more into that today.

**Comment by tupui** [comment]
@willu47 I found the issue and fixed it, now it builds fine and it's also faster 😃

**Comment by tupui** [comment]
I think this is in a good shape and doc rewrite could happen in follow up work.

**Review by willu47 — APPROVED** [review]

**Pull request merged**
