### PR TITLE
Sobol': Handle zero variance edge case

### PR DESCRIPTION
**Pull request by ConnectedSystems**
As in title - handle cases where there is no variance (e.g., a constant array) but the reported variance is > 0 due to computational error.

### CODE REVIEW

**Comment by willu47** [comment]
Interesting case. Will you provide a test? This might be an issue with other methods as well.

**Comment by ConnectedSystems** [comment]
Yes, will write a test for this.

Details are similar if not identical to this one:
https://github.com/SALib/SALib/issues/344

**Comment by ConnectedSystems** [comment]
Added tests, but open for additional comments.

Tests could probably extended to cover all other methods in the future.

**Comment by ConnectedSystems** [comment]
I believe this should be ready for review now.

**Review by tupui — APPROVED** [review]
Changes are straightforward and seem fine.

An extra thing to consider could be to have a warning when that happens. That could help some users diagnostic an issue with their modeling.

**Comment by ConnectedSystems** [comment]
Added a warning: 

    Constant values encountered, indicating the model evaluations (or subset of evaluations) produced identical values.

The warning is raised when this condition is encountered for first and second order calculations. No warnings are raised when bootstrapping.

Would appreciate feedback on whether this message is informative enough.

**Pull request merged**
