### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tupui**
This PR

- Bump minimal Python version
- Update deps
- Use hatch-vcs to simplify the release process. Instead people can access all metadata with `importlib.metadata.version("SALib")`. See https://docs.python.org/3/library/importlib.metadata.html

### CODE REVIEW

**Comment by tupui** [comment]
Ok the CI is also fixed for mamba updating Python. Before we had the same version running on both jobs.

**Comment by tupui** [comment]
Ooops will revert the change for direction...

**Comment by tupui** [comment]
@ConnectedSystems this is in good shape now, madness is fixed 😄

**Comment by ConnectedSystems** [comment]
> Ok the CI is also fixed for mamba updating Python. Before we had the same version running on both jobs.

Wow, thanks for catching that.

Everything looks good

**Comment by tupui** [comment]
Thanks :)

**Pull request merged**
