### PR TITLE
Please revise the code for Sobol and fast

### PR DESCRIPTION
**Pull request by mlmaskey**
These two files contain code that returns NaN values. If I am wrong, please let me know how to solve.
Is there a  way to  upgrade package with updated codes?
Thanks

### CODE REVIEW

**Comment by tupui** [comment]
Hi @mlmaskey, thank you for reporting.

I am afraid you cannot do that. (Not 100% sure for Fast, as I am not using it.) Sobol' requires a specific set of points to work as intended. If you remove just a single point from the sequence, then it loses its properties. Most importantly in this case, the points are "connected" with each others so if you remove one point, you have to remove the other. Still, this would break the properties of the Sobol' sequence.

What to do here depends on your problem. When you have NaNs, maybe you can replace them with a constant or some other values. Or maybe you have to change the bounds or distributions of your input parameters.

**Comment by willu47** [comment]
There are some useful discussions on missing data in the issue tracker. For example #237 and #134.  I hope those will help you find a solution for your case.

I'm going to close this PR, as SALib should fail to calculate sensitivity indices when there is missing data.  It is up to the user to provide valid data.

**Comment by tupui** [comment]
@willu47 maybe we could add some input validation in general to gracefully error out?

**Comment by willu47** [comment]
Hi @tupui - yes, that's a good idea. Providing some links in the error message to relevant issues where this is discussed could also help. There's probably also a paper to be written on this topic!

**Comment by tupui** [comment]
That's for sure, don't tease me too much 😉

**Pull request closed without merging**
